package format;

public enum TransformType {
    STUDENTTOUNITE,STUDENTTOS,STUDENTTOC,STUDENTTOM,
    COURSETOUNITE,COURSETOS,COURSETOC,COURSETOM,
    SELECTIONTOUNITE,SELECTIONTOS,SELECTIONTOC,SELECTIONTOM
}
