package xslt;

public enum TramsformType {
    STUDENTTOUNITE,STUDENTTOS,STUDENTTOC,STUDENTTOM,
    COURSETOUNITE,COURSETOS,COURSETOC,COURSETOM,
    SELECTIONTOUNITE,SELECTIONTOS,SELECTIONTOC,SELECTIONTOM
}
